services:
  app:
    container_name: cbiang-frontend
    build:
      context: ./app
      dockerfile: Dockerfile
    image: biang-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  backend:
    container_name: cbiang-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: biang-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    env_file: .environment

  db:
    container_name: cbiang-db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: biang-db
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    command: mongod --quiet --logpath /dev/null
